version: '3'

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    volumes:
      - ./configuration.yaml:/app/data/configuration.yaml
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
