version: '3'

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    volumes:
      - ./volumes/data:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
